name: Redeem Kingdom Story Coupon

on:
  repository_dispatch:
    types: [redeem-gift-code]
  workflow_dispatch:
    inputs:
      coupon_code:
        description: 'Gift code to redeem'
        required: true
        default: 'kingdom'
        type: string
      servers:
        description: 'Servers to run on (comma-separated, leave empty for all)'
        required: false
        default: ''
        type: string

jobs:
  redeem-coupon:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Run coupon redemption (repository_dispatch)
      if: github.event_name == 'repository_dispatch'
      env:
        COUPON_CODE: ${{ github.event.client_payload.gift_code }}
        SERVERS: ${{ join(github.event.client_payload.servers, ',') }}
      run: |
        echo "Redeeming gift code: ${{ github.event.client_payload.gift_code }}"
        python main.py "${{ github.event.client_payload.gift_code }}"
    
    - name: Run coupon redemption (manual)
      if: github.event_name == 'workflow_dispatch'
      env:
        COUPON_CODE: ${{ inputs.coupon_code }}
        SERVERS: ${{ inputs.servers }}
      run: |
        echo "Redeeming gift code: ${{ inputs.coupon_code }}"
        python main.py "${{ inputs.coupon_code }}"  